repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.9.0, types-redis>=4.6.0]
        args: [--ignore-missing-imports]
        files: ^core/backend/src/

  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        entry: dart format --set-exit-if-changed
        language: system
        types: [dart]
      - id: dart-analyze
        name: dart analyze
        entry: dart analyze --fatal-infos
        language: system
        types: [dart]
        pass_filenames: false
