"""Psitta API schemas package."""

from psitta.schemas.api import (
    DocumentListResponse,
    DocumentResponse,
    DocumentUploadResponse,
    ErrorResponse,
    HealthResponse,
    PaginationParams,
    PlaybackPositionUpdate,
    PlaybackSessionCreate,
    PlaybackSessionResponse,
    UserPreferencesResponse,
    UserPreferencesUpdate,
    UserProfileResponse,
    UserProfileUpdate,
    VoiceListResponse,
    VoiceProfileResponse,
    VoiceProfileUpdate,
    VoiceResponse,
)

__all__ = [
    "DocumentListResponse",
    "DocumentResponse",
    "DocumentUploadResponse",
    "ErrorResponse",
    "HealthResponse",
    "PaginationParams",
    "PlaybackPositionUpdate",
    "PlaybackSessionCreate",
    "PlaybackSessionResponse",
    "UserPreferencesResponse",
    "UserPreferencesUpdate",
    "UserProfileResponse",
    "UserProfileUpdate",
    "VoiceListResponse",
    "VoiceProfileResponse",
    "VoiceProfileUpdate",
    "VoiceResponse",
]
